routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['XSS']], function () {
    //for sms test purpose
    Route::get('/sms', 'SmsController@sendSms')->name('sms');

    Route::get('/', 'IndexController@index')->name('index');
    Route::get('/browse-restaurant', 'IndexController@browseRestaurant')->name('browseRestaurant');
    Route::get('/featured-restaurant-by-ajax', 'IndexController@featuredRestaurantByAjax')->name('featuredRestaurantByAjax');
    Route::get('/restaurant-by-ajax', 'IndexController@restaurantByAjax')->name('restaurantByAjax');
    Route::get('/show-restaurant/{slug}', 'IndexController@restaurant')->name('restaurant.single');
    Route::get('/show-floor-with-tables-ajax', 'IndexController@getFloorWithTable');


    Route::get('/get-food-meny-by-ajax', 'IndexController@getFoodMenuByAjax')->name('getFoodMenuByAjax');


    Route::get('/cuisine', 'IndexController@restaurantByCuisine')->name('restaurantByCuisine');
    Route::get('/cuisine-restaurant-by-ajax', 'IndexController@cuisineRestaurantByAjax')->name('cuisineRestaurantByAjax');

    //Delivery option
    Route::post('/set-delivery-option-by-ajax', 'IndexController@deliveryOption')->name('deliveryOption');


    //cart
    Route::post('/add-to-cart-by-ajax', 'OnlineCartController@addToCartByAjax')->name('addToCartByAjax');
    Route::post('/edit-to-cart-by-ajax', 'OnlineCartController@editToCartByAjax')->name('editToCartByAjax');
    Route::post('/delete-from-cart-by-ajax', 'OnlineCartController@deleteFromCartByAjax')->name('deleteFromCartByAjax');





    Route::group(['prefix' => 'SuperAdmin'], function () {
        Route::get('/payment','SuperAdminPaymentController@payment')->name('superAdmin.payment');
        Route::get('/addpayment','SuperAdminPaymentController@addPayment')->name('superAdmin.addPayment');

        Route::get('/report','SuperAdminPaymentController@report')->name('superAdmin.report');

        //ROLE Controller//
        Route::get('/role','SuperAdminRoleController@role')->name('superAdmin.role');
        Route::get('/add_role','SuperAdminRoleController@addrole')->name('superAdmin.add_role');
        Route::post('/role_insert','SuperAdminRoleController@roleinsert')->name('superAdmin.role_insert');
        Route::get('/Edit-Role/{id}','SuperAdminRoleController@edit_role')->name('Edit-Role');
        Route::get('/Delete-Role/{id}','SuperAdminRoleController@delete_role')->name('Delete-Role');
        Route::post('/update-role', 'SuperAdminRoleController@updaterole')->name('update-role');


        //-----Active Restaurant -------------
        Route::get('/active-restaurant','SuperAdminRoleController@activerestaurant')->name('superAdmin.active-restaurant');
        Route::get('/status-update/{id}','SuperAdminRoleController@updatestatus')->name('superAdmin.status-update');

        //------------Add New Restaurant--------
        Route::get('/add-new-restaurant','SuperAdminRoleController@showForm')->name('superAdmin.add-new-restaurant');
        Route::post('/add-rs','SuperAdminRoleController@addnewRestaurant')->name('add-rs');





        // --------Restaurant List ------------------
        Route::get('/supr-restaurant-list','SuperAdminRoleController@restaurantlist')->name('supr-restaurant-list');
        Route::get('/Restaurant-role/{id}','SuperAdminRoleController@restaurantRole')->name('superAdmin.Restaurant-role');
        Route::get('/Payment-res/{id}','SuperAdminRoleController@paymentRes')->name('SuperAdmin/Payment-res');
        Route::post('/res-Payment-add','SuperAdminRoleController@addpaymentRes')->name('res-Payment-add');






        //------------Payment Getway to Restaurant------------------------
        Route::get('/Payment-Restaurant','SuperAdminRoleController@PaymentGetwaytoRestaurant')->name('Payment-Restaurant');
        Route::post('/add-Payment-Restaurant','SuperAdminRoleController@addPaymentGateway')->name('add-Payment-Restaurant');
        Route::post('/active-Payment-Restaurant','SuperAdminRoleController@activePaymentRestaurant')->name('active-Payment-Restaurant');
       // Route::post('/active-Restaurant-acp','SuperAdminRoleController@activeRestaurantAcp')->name('active-Restaurant-acp');


        //--------------Email Settings--------------------
        Route::get('/Email-Settings','SuperAdminRoleController@EmailSettings')->name('Email-Settings');


        //-------------------SMS-Settings

        Route::get('/SMS-Settings','SuperAdminRoleController@smsSettings')->name('SMS-Settings');



        //-----Restaurant Report-------------
    Route::get('/report-restaurant','SuperAdminRoleController@restaurantreport')->name('superAdmin.restaurant-report');


       // Route::post('/add-permissions', 'SuperAdminRoleController@addpermissions')->name('add-permissions');




//------------------STAFF-------------------//
        Route::get('/Staff','SuperAdminRoleController@staff')->name('superAdmin.Staff');
        Route::post('/add-staff','SuperAdminRoleController@addstaff')->name('superAdmin.add-staff');





        Route::get('/SALogin', 'SuperAdminAuthController@showLoginForm')->name('superAdmin.showLoginForm');
        Route::post('/SALogin', 'SuperAdminAuthController@doLogin')->name('superAdmin.doLogin');

        Route::get('/logout', 'SuperAdminAuthController@logout')->name('superAdmin.logout');

        Route::get('/dashboard', 'SuperAdminDashboardController@dashboard')->name('superAdmin.dashboard');

        //all ---------------------
        Route::get('/other_list', 'SuperAdminDashboardController@otherlist')->name('superAdmin.other_list');
        Route::get('/All-Service', 'SuperAdminDashboardController@allService')->name('superAdmin.All-Service');
        Route::get('/Sale', 'SuperAdminDashboardController@sale')->name('superAdmin.Sale');
        Route::get('/Inventory', 'SuperAdminDashboardController@inventory')->name('superAdmin.Inventory');
        Route::get('/Inventory_Adjustment', 'SuperAdminDashboardController@inventoryadjustment')->name('superAdmin.Inventory_Adjustment');
        Route::get('/waste', 'SuperAdminDashboardController@waste')->name('superAdmin.waste');







        Route::group(['prefix' => 'settings'], function () {

            Route::get('', 'SuperAdminSettingsController@index')->name('superAdmin.settings');

            Route::resource('countries', 'CountriesController');
            Route::get('countries/{id}/delete', 'CountriesController@delete')->name('countries.delete');
            Route::post('countries-csv', 'CountriesController@csvadd')->name('countries.csv');


            Route::resource('states', 'StatesController');
            Route::get('states/{id}/delete', 'StatesController@delete')->name('states.delete');

            Route::resource('cities', 'CitiesController');
            Route::get('cities/{id}/delete', 'CitiesController@delete')->name('cities.delete');

            Route::resource('cuisines', 'CuisinesController');
            Route::get('cuisines/{id}/delete', 'CuisinesController@delete')->name('cuisines.delete');

            Route::get('privacy-policy', 'PrivacyPoliciesController@show')->name('privacyPolicies.show');
            Route::put('privacy-policy/{id}', 'PrivacyPoliciesController@update')->name('privacyPolicies.update');

            Route::resource('social-media', 'SocialMediaController');
            Route::get('social-media/{id}/delete', 'SocialMediaController@delete')->name('social-media.delete');

            Route::resource('third-party-vendors', 'ThirdPartyVendorsController');
            Route::get('third-party-vendors/{id}/delete', 'ThirdPartyVendorsController@delete')->name('third-party-vendors.delete');

            Route::resource('charges', 'ChargesController');
            Route::get('charges/{id}/delete', 'ChargesController@delete')->name('charges.delete');



        });

        Route::get('/restaurant-list', 'SuperAdminRestaurantsController@restaurantList')->name('superAdmin.restaurantList');
        Route::get('/restaurant-list/{id}', 'SuperAdminRestaurantsController@viewDetail')->name('superAdmin.restaurantList.viewDetail');
        Route::get('/restaurant-list/{id}/approve', 'SuperAdminRestaurantsController@approve')->name('superAdmin.restaurantList.approve');
        Route::get('/restaurant-list/{id}/disapprove', 'SuperAdminRestaurantsController@disapprove')->name('superAdmin.restaurantList.disapprove');

        Route::get('/restaurant-list/{id}/featured', 'SuperAdminRestaurantsController@featured')->name('superAdmin.restaurantList.featured');
        Route::get('/restaurant-list/{id}/non-featured', 'SuperAdminRestaurantsController@nonFeatured')->name('superAdmin.restaurantList.nonFeatured');

        Route::get('/restaurant-list/{id}/delete', 'SuperAdminRestaurantsController@delete')->name('superAdmin.restaurantList.delete');

        Route::post('/add-restaurant-charge-by-ajax', 'SuperAdminRestaurantsController@addRestaurantChargeByAjax')->name('superAdmin.addRestaurantChargeByAjax');

        Route::post('/edit-restaurant-charge-by-ajax', 'SuperAdminRestaurantsController@editRestaurantChargeByAjax')->name('superAdmin.editRestaurantChargeByAjax');


    });

    Route::group(['prefix' => 'restaurant'], function () {
        Route::get('/sign-up', 'RestaurantAuthController@showSignUpForm')->name('restaurant.showSignUpForm');
        Route::post('/sign-up', 'RestaurantAuthController@doSignUp')->name('restaurant.doSignUp');
        Route::get('/verify/{token}', 'RestaurantVerifyController@restaurantVerifyEmail')->name('restaurant.verifyEmail');

app/SuperAdmin.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class SuperAdmin extends Authenticatable
{
    use Notifiable;

    protected $table = 'tbl_super_admins';

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
    ];
}

resources/views/layouts/superAdmin/header.blade.php
<?php
$baseURL = getBaseURL();
?>

<header class="main-header">
    <!-- Logo -->
    <a href="#" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini">AMP</span>
        <!-- logo for regular state and mobile devices -->

        <span class="logo-lg">
                        Ask Me POS
            </span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li style="padding-top:15px">
                    <p style="padding:0 10px"><b>{{Auth::guard('superAdmin')->user()->user_name}}</b></p>
                </li>
                <li class="dropdown user user-menu">
                    <a href="{{route('superAdmin.logout')}}">Logout
                    </a>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/layouts/superAdmin/sidebar.blade.php
<?php
$baseURL = getBaseURL();
?>

<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <ul class="sidebar-menu">
            <li class="header">Main Navigation</li>
        </ul>
        <div id="left_menu_to_scroll">
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu" data-widget="tree">
                <li>
                    <a href="{{route('superAdmin.dashboard')}}">
                        <i data-feather="home"></i> <span>Home</span></a>
                </li>
                <li>
                    <a href="{{route('superAdmin.other_list')}}">
                        <i data-feather="list"></i> <span>Other List</span></a>
                </li>
                <li>
                    <a href="{{route('superAdmin.All-Service')}}">
                        <i data-feather="server"></i> <span>All Service</span></a>
                </li>


                <li class="treeview">
                    <a href="#">
                        <i data-feather="activity"></i> <span>Restaurant</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">

                        <li><a href="{{route('superAdmin.active-restaurant')}}"><i class="fa fa-angle-double-right"></i>Active Restaurant</a></li>
                        <li><a href="{{route('supr-restaurant-list')}}"><i class="fa fa-angle-double-right"></i>Restaurant List</a></li>
                        <li><a href="{{route('superAdmin.add-new-restaurant')}}"><i class="fa fa-angle-double-right"></i>Add Restaurant</a></li>
                        <li><a href="{{route('superAdmin.restaurant-report')}}"><i class="fa fa-angle-double-right"></i>Restaurant Report</a></li>
                    </ul>
                </li>


                <li class="treeview">
                    <a href="{{route('superAdmin.settings')}}">
                        <i data-feather="settings"></i> <span>Settings</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="#"><i class="fa fa-angle-double-right"></i>Google Map API setting</a></li>
                        <li><a href="{{route('Payment-Restaurant')}}"><i class="fa fa-angle-double-right"></i>Payment Gateway Setting</a></li>
                        <li><a href="{{route('countries.index')}}"><i class="fa fa-angle-double-right"></i>Countries</a>
                        </li>
                        <li><a href="{{route('Email-Settings')}}"><i class="fa fa-angle-double-right"></i>Email Settings</a></li>
                        <li><a href="{{route('SMS-Settings')}}"><i class="fa fa-angle-double-right"></i>SMS Settings</a></li>
                        <li><a href="{{route('states.index')}}"><i class="fa fa-angle-double-right"></i>States</a></li>
                        <li><a href="{{route('cities.index')}}"><i class="fa fa-angle-double-right"></i>Cities</a></li>
                        <li><a href="{{route('cuisines.index')}}"><i class="fa fa-angle-double-right"></i>Cuisines</a>
                        </li>
                        <li><a href="{{route('privacyPolicies.show')}}"><i class="fa fa-angle-double-right"></i>Privacy
                                Policy</a></li>
                        <li><a href="{{route('social-media.index')}}"><i class="fa fa-angle-double-right"></i>Social
                                Media</a></li>
                        <li><a href="{{route('third-party-vendors.index')}}"><i class="fa fa-angle-double-right"></i>3rd
                                Parties Venders</a></li>
                        <li><a href="{{route('charges.index')}}"><i class="fa fa-angle-double-right"></i>Fee Charges</a>
                        </li>
                    </ul>
                </li>
               {{-- <li>
                    <a href="{{route('superAdmin.restaurantList')}}">
                        <i data-feather="align-center"></i> <span>Restaurant List</span></a>
                </li>--}}

                <li class="treeview">
                    <a href="">
                        <i data-feather="sliders"></i> <span>Report</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href=""><i class="fa fa-angle-double-right"></i>Register Report</a></li>
                        <li><a href=""><i class="fa fa-angle-double-right"></i>Daily Summaery Report</a></li>
                        <li><a href=""><i class="fa fa-angle-double-right"></i>Food Sale Report</a></li>
                        <li><a href=""><i class="fa fa-angle-double-right"></i>Daily Sale Report</a></li>
                        <li><a href=""><i class="fa fa-angle-double-right"></i>Detailed Sale Report</a>
                        </li>
                        <li><a href=""><i class="fa fa-angle-double-right"></i>Consumption Report</a>
                        </li>
                        <li><a href=""><i class="fa fa-angle-double-right"></i>Inventory Report</a>
                        </li>
                        <li><a href=""><i class="fa fa-angle-double-right"></i>Low Inventory Report</a></li>
                        <li><a href=""><i class="fa fa-angle-double-right"></i>Profit Loss Report</a>
                        </li>
                        <li><a href=""><i class="fa fa-angle-double-right"></i>Kitchen Performance Report</a>
                        </li>
                        <li><a href=""><i class="fa fa-angle-double-right"></i>Attendance Report</a></li>
                        <li><a href=""><i class="fa fa-angle-double-right"></i>Supplier Ledger</a></li>
                        <li><a href=""><i class="fa fa-angle-double-right"></i>Supplier Due Report</a></li>
                        <li><a href=""><i class="fa fa-angle-double-right"></i>Customer Due Report</a></li>
                        <li><a href=""><i class="fa fa-angle-double-right"></i>Customer Ledger</a></li>
                        <li><a href="{{route('charges.index')}}"><i class="fa fa-angle-double-right"></i>Purchase Report</a>
                        </li>
                        <li><a href=""><i class="fa fa-angle-double-right"></i>Expense Report</a></li>
                        <li><a href=""><i class="fa fa-angle-double-right"></i>Waste Report</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </section>
    <!-- /.sidebar -->
</aside>